# Generated by Django 5.2.3 on 2025-06-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
