# Generated by Django 5.2.3 on 2025-07-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='dage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='dcontact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient_profile',
            name='pcontact',
            field=models.IntegerField(),
        ),
    ]
